'use strict';

window.PAINTING_TITLES = Object.freeze({
  "BaiLu": { zh: "白鹭", en: "Egret" },
  "BaiShi_HePing": { zh: "临齐白石《和平》", en: "After Qi Baishi: Peace" },
  "BaiShi_JiuLongTu": { zh: "临齐白石《九龙图》", en: "After Qi Baishi: Nine Dragons" },
  "BaiShi_LuoBo": { zh: "临齐白石《萝卜》", en: "After Qi Baishi: Radishes" },
  "BaiShi_SiGua": { zh: "临齐白石《丝瓜》", en: "After Qi Baishi: Loofah Gourds" },
  "BaiShi_Yu": { zh: "临齐白石《鱼》", en: "After Qi Baishi: Fish" },
  "BaiYunShanZhong1": { zh: "白云山中（一）", en: "Among the White Clouds I" },
  "BaiYunShanZhong2": { zh: "白云山中（二）", en: "Among the White Clouds II" },
  "bridge": { zh: "桥", en: "Bridge Study" },
  "CaoZhangYingFei": { zh: "草长莺飞", en: "Spring Grass and Flying Orioles" },
  "cat": { zh: "猫", en: "Cat Study" },
  "ChaHua": { zh: "茶花", en: "Camellias" },
  "ChangCheng_BeiJing": { zh: "长城·北京", en: "The Great Wall, Beijing" },
  "ChangCheng_WangLiXiongGuan1": { zh: "长城·万里雄关（一）", en: "The Great Wall: Mighty Passes I" },
  "ChangCheng_WangLiXiongGuan2": { zh: "长城·万里雄关（二）", en: "The Great Wall: Mighty Passes II" },
  "ChangCheng_WangLiXiongGuan3": { zh: "长城·万里雄关（三）", en: "The Great Wall: Mighty Passes III" },
  "ChangCheng_WangLiXiongGuan4": { zh: "长城·万里雄关（四）", en: "The Great Wall: Mighty Passes IV" },
  "ChangCheng_XGWL1": { zh: "长城·雄关万里（一）", en: "The Great Wall Across Ten Thousand Li I" },
  "ChangCheng_XGWL2": { zh: "长城·雄关万里（二）", en: "The Great Wall Across Ten Thousand Li II" },
  "ChangCheng_XiongGuanWanLi1": { zh: "长城·雄关万里（一）", en: "The Great Wall Across Ten Thousand Li I" },
  "ChangCheng_XiongGuanWanLi2": { zh: "长城·雄关万里（二）", en: "The Great Wall Across Ten Thousand Li II" },
  "ChangCheng_XiongGuanWanLi3": { zh: "长城·雄关万里（三）", en: "The Great Wall Across Ten Thousand Li III" },
  "cherry": { zh: "樱桃速写", en: "Cherry Sketch" },
  "ChuiDiao": { zh: "垂钓", en: "Angling" },
  "ChunFengSongNuan": { zh: "春风送暖", en: "Spring Breeze Brings Warmth" },
  "DaJiDaLi": { zh: "大吉大利", en: "Great Fortune and Prosperity" },
  "DaPengZhangChi": { zh: "大鹏展翅", en: "The Roc Spreads Its Wings" },
  "DaXieYi-BaJiao": { zh: "芭蕉", en: "Banana Leaves" },
  "DaXieYi-HuLu-NanGua-DaXieYi": { zh: "葫芦南瓜", en: "Gourds & Pumpkin" },
  "DaXieYi-JuHua-DaXieYi": { zh: "菊花", en: "Chrysanthemums" },
  "DaXieYi-LanCao": { zh: "兰草", en: "Orchid Grass" },
  "DaXieYi-MoYeHeHua": { zh: "墨叶荷花", en: "Ink Lotus" },
  "DaXieYi-SongShu-DaXieYi": { zh: "松树", en: "Pine Tree" },
  "DianCun1": { zh: "点皴（一）", en: "Dot-Texture Study I" },
  "DianCun2": { zh: "点皴（二）", en: "Dot-Texture Study II" },
  "DianYeChengJin": { zh: "点叶成金", en: "Leaves Touched with Gold" },
  "FeiPu": { zh: "飞瀑", en: "Cascading Waterfall" },
  "FengHuaJueDai": { zh: "风华绝代", en: "Peerless Elegance" },
  "FengHuaJueDai1": { zh: "风华绝代（一）", en: "Peerless Elegance I" },
  "fengHuaJueDai2": { zh: "风华绝代（二）", en: "Peerless Elegance II" },
  "FengHuaJueDai3": { zh: "风华绝代（三）", en: "Peerless Elegance III" },
  "FuRong": { zh: "芙蓉（一）", en: "Hibiscus I" },
  "FuRong_2": { zh: "芙蓉（二）", en: "Hibiscus II" },
  "FuRongJinJi": { zh: "芙蓉锦鸡", en: "Hibiscus and Golden Pheasant" },
  "GongXi": { zh: "恭喜", en: "Congratulations" },
  "GreatWall": { zh: "长城图", en: "The Great Wall" },
  "GreatWall-XiongGuanWanLi": { zh: "雄关万里", en: "The Great Pass" },
  "GuanPuTu": { zh: "观瀑图", en: "Viewing the Waterfall" },
  "GuanShangJiaGuan": { zh: "冠上加冠", en: "Crown upon Crown" },
  "GuanShangJiaGuan_BaiShi": { zh: "临齐白石《冠上加冠》", en: "After Qi Baishi: Crown upon Crown" },
  "HeHua_BiShuiHeXian": { zh: "荷花·碧水荷仙", en: "Lotus Immortal on Emerald Waters" },
  "HeHua_QingHeYaZhi": { zh: "荷花·清荷雅致", en: "Elegant Lotus" },
  "HeHua_TingTingYuLi": { zh: "荷花·亭亭玉立", en: "Lotus Standing Gracefully" },
  "HeHua_XiangYingChengQu": { zh: "荷花·相映成趣", en: "Lotus in Harmonious Reflection" },
  "HeHua_XiuHuaHeKai": { zh: "荷花盛开", en: "Lotus in Bloom" },
  "HeHuaQingTing": { zh: "荷花蜻蜓", en: "Lotus and Dragonfly" },
  "HeTangCuiNiao": { zh: "荷塘翠鸟", en: "Kingfisher at the Lotus Pond" },
  "HeTangHuanLe": { zh: "荷塘欢乐", en: "Joy at the Lotus Pond" },
  "HeTangYueYe": { zh: "荷塘月夜", en: "Moonlit Lotus Pond" },
  "HongMei_1": { zh: "红梅（一）", en: "Red Plum Blossoms I" },
  "HongMei2": { zh: "红梅（二）", en: "Red Plum Blossoms II" },
  "Hu_ShangShanHu1": { zh: "上山虎（一）", en: "Ascending Tiger I" },
  "Hu_ShangShanHu2": { zh: "上山虎（二）", en: "Ascending Tiger II" },
  "Hu_ShangShanHu3": { zh: "上山虎（三）", en: "Ascending Tiger III" },
  "Hu_ShangShanHu4": { zh: "上山虎（四）", en: "Ascending Tiger IV" },
  "Hu_ShangShanHu5": { zh: "上山虎（五）", en: "Ascending Tiger V" },
  "Hu_XiaShangHu22": { zh: "下山虎（22）", en: "Descending Tiger 22" },
  "Hu_XiaShanHu0": { zh: "下山虎（0）", en: "Descending Tiger 0" },
  "Hu_XiaShanHu1": { zh: "下山虎（一）", en: "Descending Tiger I" },
  "Hu_XiaShanHu2": { zh: "下山虎（二）", en: "Descending Tiger II" },
  "Hu_XiaShanHu21": { zh: "下山虎（21）", en: "Descending Tiger 21" },
  "HuaKaiFuGui": { zh: "花开富贵", en: "Blossoming Prosperity" },
  "HuaKaiFuGui1": { zh: "花开富贵（一）", en: "Blossoming Prosperity I" },
  "HuaKaiFuGui2": { zh: "花开富贵（二）", en: "Blossoming Prosperity II" },
  "HuaKaiFuGui3": { zh: "花开富贵（三）", en: "Blossoming Prosperity III" },
  "HuaKaiYinDie": { zh: "花开引蝶", en: "Blossoms Beckon Butterflies" },
  "HuangGuoShuPuBu1": { zh: "黄果树瀑布（一）", en: "Huangguoshu Waterfall I" },
  "HuangGuoShuPuBu2": { zh: "黄果树瀑布（二）", en: "Huangguoshu Waterfall II" },
  "HuangShanYunHai": { zh: "黄山云海", en: "Sea of Clouds at Huangshan" },
  "HuangShanYunHai1": { zh: "黄山云海（一）", en: "Sea of Clouds over Huangshan I" },
  "HuangShanYunHai2": { zh: "黄山云海（二）", en: "Sea of Clouds over Huangshan II" },
  "huaniao1": { zh: "花鸟习作之一", en: "Flora & Fauna Study I" },
  "huaniao2": { zh: "花鸟习作之二", en: "Flora & Fauna Study II" },
  "HuaShanYunHai1": { zh: "华山云海（一）", en: "Sea of Clouds over Mount Hua I" },
  "JieZiYuan_ZheZhiHuaHui1": { zh: "芥子园·折枝花卉（一）", en: "Mustard Seed Garden: Flowering Branches I" },
  "JieZiYuan_ZheZhiHuaHui2": { zh: "芥子园·折枝花卉（二）", en: "Mustard Seed Garden: Flowering Branches II" },
  "JiMingZiTeng": { zh: "鸡鸣紫藤", en: "Rooster's Call beneath Wisteria" },
  "JinBiShanShui": { zh: "金碧山水", en: "Blue and Green Landscape" },
  "JinJiFuGui": { zh: "锦鸡富贵", en: "Golden Pheasant" },
  "JinJiMuDan": { zh: "锦鸡牡丹", en: "Golden Pheasant and Peonies" },
  "JinQiu": { zh: "金秋", en: "Golden Autumn" },
  "JinSiHuDie": { zh: "金丝蝴蝶", en: "Golden-Thread Butterfly" },
  "JinSiJu1": { zh: "金丝菊（一）", en: "Golden Chrysanthemums I" },
  "JinYuManTang": { zh: "金玉满堂", en: "A Hall Filled with Gold and Jade" },
  "JuHua": { zh: "菊花", en: "Chrysanthemums" },
  "JuHua_JinSiJu": { zh: "菊花·金丝菊", en: "Golden Chrysanthemums" },
  "JunMaTu1": { zh: "骏马图（一）", en: "Galloping Steeds I" },
  "JunMaXiaoQiTu": { zh: "骏马长啸图", en: "Neighing Steed" },
  "JunZiZhiFeng-ZhuJuTu": { zh: "君子之风·竹菊图", en: "The Gentleman's Spirit: Bamboo and Chrysanthemums" },
  "KanShan": { zh: "看山", en: "Contemplating the Mountains" },
  "KongQue_FuGuiChengXiang": { zh: "孔雀·富贵呈祥", en: "Peacock: Prosperity and Auspiciousness" },
  "LiJiangShanShui1": { zh: "漓江山水（一）", en: "Li River Landscape I" },
  "LiJiangShanShui2": { zh: "漓江山水（二）", en: "Li River Landscape II" },
  "Lin_QianLIJianShan_JuBu": { zh: "临《千里江山图》局部", en: "Detail after A Thousand Li of Rivers and Mountains" },
  "LingXiao_MaQue": { zh: "凌霄麻雀", en: "Trumpet Vine and Sparrows" },
  "LingXiaoHua_2": { zh: "凌霄花（二）", en: "Trumpet Vine II" },
  "LiZhi": { zh: "荔枝", en: "Lychees" },
  "LiZhi_NanGuoLiZhi": { zh: "荔枝·南国荔枝", en: "Lychees of the South" },
  "MeiHua_LaMei": { zh: "梅花·腊梅", en: "Wintersweet" },
  "MengHu": { zh: "猛虎图", en: "Fierce Tiger" },
  "MengHuXiaShan": { zh: "猛虎下山", en: "Tiger Descending the Mountain" },
  "MoZhu": { zh: "墨竹", en: "Ink Bamboo" },
  "MuDan_ChiYangHongXia": { zh: "牡丹·赤阳红霞", en: "Peony: Crimson Sunlit Clouds" },
  "MuDan_DieDanTu": { zh: "牡丹·蝶丹图", en: "Peonies and Butterflies" },
  "MuDan_DieLianHua": { zh: "牡丹·蝶恋花", en: "Peony: Butterfly in Love with Blossoms" },
  "MuDan_DieLianHua2": { zh: "牡丹·蝶恋花（二）", en: "Peony: Butterfly in Love with Blossoms II" },
  "MuDan_JinFeng": { zh: "牡丹·金凤", en: "Peony: Golden Phoenix" },
  "MuDan_JiXiangHuaKai": { zh: "牡丹·吉祥花开", en: "Peony: Auspicious Blossoms" },
  "MuDan_LuoYangMuDan": { zh: "牡丹·洛阳牡丹", en: "Peonies of Luoyang" },
  "MuDan_LuYi": { zh: "牡丹·绿衣", en: "Peony in Green" },
  "MuDan_YuCuiLanYun": { zh: "牡丹·玉翠蓝韵", en: "Peony: Jade Green and Azure Rhythm" },
  "MuDan_ZiXiaXianZi": { zh: "牡丹·紫霞仙子", en: "Peony: Violet-Cloud Fairy" },
  "PuTao1": { zh: "葡萄（一）", en: "Grapes I" },
  "QianNiu": { zh: "牵牛花", en: "Morning Glories" },
  "QingGong2": { zh: "清供（二）", en: "Scholar's Offerings II" },
  "QingGong3": { zh: "清供（三）", en: "Scholar's Offerings III" },
  "QingYin": { zh: "清音", en: "Pure Notes" },
  "QiuYun": { zh: "秋韵", en: "Autumn Rhythm" },
  "RenAi": { zh: "仁爱", en: "Benevolence" },
  "sailboat": { zh: "帆船速写", en: "Sailboat Sketch" },
  "ShanChaHua": { zh: "山茶花", en: "Camellias" },
  "ShiShiRuYi": { zh: "事事如意", en: "May All Go as You Wish" },
  "ShiZi_XiShuai": { zh: "柿子蟋蟀", en: "Persimmons and Cricket" },
  "ShouTao1": { zh: "寿桃（一）", en: "Peaches of Longevity I" },
  "ShuiXian": { zh: "水仙", en: "Narcissus" },
  "SiGua": { zh: "丝瓜", en: "Loofah Gourds" },
  "SiTiaoPing_JuHua": { zh: "四条屏·菊花", en: "Four-Panel Set: Chrysanthemums" },
  "SiTiaoPing_LanHua": { zh: "四条屏·兰花", en: "Four-Panel Set: Orchids" },
  "SiTiaoPing_MeiHua": { zh: "四条屏·梅花", en: "Four-Panel Set: Plum Blossoms" },
  "SiTiaoPing_Zhu": { zh: "四条屏·竹", en: "Four-Panel Set: Bamboo" },
  "SnowBamboo": { zh: "雪竹", en: "Bamboo in Snow" },
  "SongHeChangQing": { zh: "松鹤长青", en: "Evergreen Pines and Cranes" },
  "SongHeTu_YouZhongGuo": { zh: "松鹤图·佑中国", en: "Pines and Cranes Bless China" },
  "SongHeYanNian": { zh: "松鹤延年", en: "Pine and Crane" },
  "SongHeYanNian1": { zh: "松鹤延年（一）", en: "Pines and Cranes for Longevity I" },
  "XiangRiKui": { zh: "向日葵", en: "Sunflowers" },
  "XiaoQiaoLiuShui": { zh: "小桥流水", en: "Little Bridge and Flowing Water" },
  "XiaoQiaoLiuShui1": { zh: "小桥流水（一）", en: "Bridge over Flowing Water I" },
  "Xie_BaXieTu": { zh: "八蟹图", en: "Eight Crabs" },
  "XiHu_HangZhou": { zh: "西湖·杭州", en: "West Lake, Hangzhou" },
  "XingJi": { zh: "雄鸡", en: "Rooster" },
  "XiongMao1": { zh: "熊猫（一）", en: "Panda I" },
  "XiongMao2": { zh: "熊猫（二）", en: "Panda II" },
  "XiQiao": { zh: "溪桥", en: "Bridge over a Mountain Stream" },
  "XiQueMuDan": { zh: "喜鹊牡丹", en: "Magpies and Peonies" },
  "XiShangMeiShao": { zh: "喜上眉梢", en: "Joy upon the Plum Branch" },
  "XiShanMuJing1": { zh: "溪山暮景（一）", en: "Evening in Stream and Mountains I" },
  "XiShanMuJing2": { zh: "溪山暮景（二）", en: "Evening in Stream and Mountains II" },
  "XiShanMuJing3": { zh: "溪山暮景（三）", en: "Evening in Stream and Mountains III" },
  "XiShanMuJing4": { zh: "溪山暮景（四）", en: "Evening in Stream and Mountains IV" },
  "XiYuXuShan": { zh: "溪雨虚山", en: "Mountain Stream in Rain" },
  "XueWu1": { zh: "雪屋（一）", en: "Snowbound Cottages I" },
  "XueWu2": { zh: "雪屋（二）", en: "Snowbound Cottages II" },
  "XueWu3": { zh: "雪屋（三）", en: "Snowbound Cottages III" },
  "XueWu4": { zh: "雪屋（四）", en: "Snowbound Cottages IV" },
  "XueWu5": { zh: "雪屋（五）", en: "Snowbound Cottages V" },
  "XueWu6": { zh: "雪屋（六）", en: "Snowbound Cottages VI" },
  "XueZhu": { zh: "雪竹", en: "Bamboo in Snow" },
  "YangZiRiver": { zh: "长江万里图", en: "Ten Thousand Miles of the Yangtze River" },
  "Ying1": { zh: "鹰（一）", en: "Eagle I" },
  "Ying2": { zh: "鹰（二）", en: "Eagle II" },
  "YingWuBaJIao": { zh: "鹦鹉芭蕉", en: "Parrot and Banana Leaves" },
  "YingWuBaJiao1": { zh: "鹦鹉芭蕉（一）", en: "Parrot and Banana Leaves I" },
  "YuanYuanLiuChang1": { zh: "源远流长（一）", en: "From a Distant Source I" },
  "YuanYuanLiuChang2": { zh: "源远流长（二）", en: "From a Distant Source II" },
  "YuanYuanLiuChang3": { zh: "源远流长（三）", en: "From a Distant Source III" },
  "YuanYuanLiuChang4": { zh: "源远流长（四）", en: "From a Distant Source IV" },
  "YuanYuanLiuChang5": { zh: "源远流长（五）", en: "From a Distant Source V" },
  "YuLan_ShangHai": { zh: "玉兰·上海", en: "Shanghai Magnolia" },
  "YuLanHua": { zh: "玉兰花", en: "Magnolias" },
  "YunHaiTu": { zh: "云海图", en: "Sea of Clouds" },
  "YuYueLongMen": { zh: "鱼跃龙门", en: "Carp Leaping the Dragon Gate" },
  "YuZhu": { zh: "雨竹", en: "Bamboo in Rain" },
  "ZhiJiHongye1": { zh: "雉鸡红叶（一）", en: "Pheasant among Red Leaves I" },
  "ZhiJiHongYe2": { zh: "雉鸡红叶（二）", en: "Pheasant among Red Leaves II" },
  "ZhongTang_JinShangTianHua": { zh: "中堂·锦上添花", en: "Hanging Scroll: Blossoms upon Brocade" },
  "ZhongTang_LanCaoTu": { zh: "中堂·兰草图", en: "Hanging Scroll: Orchids" },
  "ZhongTang_ManShanHongBian1": { zh: "中堂·满山红遍（一）", en: "Hanging Scroll: Mountains Ablaze in Red I" },
  "ZhongTang_ManShanHongBian2": { zh: "中堂·满山红遍（二）", en: "Hanging Scroll: Mountains Ablaze in Red II" },
  "ZhongTang_PuTaoDuoFu": { zh: "中堂·葡萄多福", en: "Hanging Scroll: Grapes of Abundant Blessings" },
  "ZiTengHua": { zh: "紫藤花", en: "Wisteria" },
  "ZiTengJinLi": { zh: "紫藤锦鲤", en: "Wisteria and Koi" }
});

